version: "3.7"

services:
  dc-nodejs-asciidoc-reveraljs:
    image: node:20
    hostname: dc-nodejs-asciidoc-reveraljs.local
    environment:
      - VAR1=${VAR1_FROM_DOT_ENV}
      - VAR2=${VAR2_FROM_DOT_ENV}
    build:
      context: .
    working_dir: /src
    volumes:
      - ..:/src:cached
    command: >
      bash -c "sleep infinity"
